FROM beevelop/cordova:latest
RUN mkdir $ANDROID_HOME/licenses

COPY android-sdk-license $ANDROID_HOME/licenses/
WORKDIR /src

RUN cordova create hello
WORKDIR /src/hello
RUN cordova platform add android
RUN cordova plugin add cordova-plugin-crosswalk-webview
COPY . /src/hello/www/
RUN cordova prepare android
